### ISSUE TITLE
Copy button

### ISSUE THREAD

**Issue by nadia-polikarpova** [davidmrdavid/hoogle_plus#46]
Next to each solution, there should be a "copy to clipboard" button.

**Comment by michaelbjames** [comment]
https://github.com/davidmrdavid/hoogle_plus/tree/mj_copy_button
Needs to be merged. Waiting for @mistzzt 's PR to merge filtering and webapp into master.

**Comment by michaelbjames** [comment]
https://github.com/davidmrdavid/hoogle_plus/pull/55
