### ISSUE TITLE
web todo: Component documentation

### ISSUE THREAD

**Issue by nadia-polikarpova** [davidmrdavid/hoogle_plus#47]
When hovering over a component, below the type signature we also want to show an excerpt from this component's hackage documentation, just like it is done in Hoogle. Moreover, clicking on the component should take you to this component's hackage documentation, just like in Hoogle.

**Comment by michaelbjames** [comment]
This is going to require:
1. handling the documentation and showing it as a tooltip on the code.
2. Getting the hackage documentation, maybe during the `generate` phase in `hplus`, or just separately
3. The middle layer serving the documentation to the UI.
