### ISSUE TITLE
Do not generate argnames for inner functions

### ISSUE THREAD

**Issue by nadia-polikarpova** [davidmrdavid/hoogle_plus#49]
The arguments of higher-order query arguments are never used in the solution, and hence should not be given names automatically.

For example: the query type `f: (a -> b) -> p: (a , a) -> (b , b)` is currently transformed into `f: (arg0: a -> b) -> p: (a , a) -> (b , b)`, but in fact should be left as is.

**Comment by shivanidoshi26** [comment]
Fixed. If someone could code review, I can put in a PR and close the issue.
