### ISSUE TITLE
Use input-output examples as specification

### ISSUE THREAD

**Issue by nadia-polikarpova** [davidmrdavid/hoogle_plus#50]
Add a filtering step to the synthesis engine that tests solutions on user-provided inputs. Can we add these manually-provided tests to Ziteng's test-based filtering framework?

Since there is a redundancy between types and tests, ideally we want to handle it as follows:
1. As a first step, we can always require a type query, type-check the examples (if any) against it, and highlight ill-typed examples
2. Infer the type from examples: if the user enters examples first, we can infer a type from these examples (but how general should it be?) and let the user edit it.
3. Suggest inputs from type: if the user enters the type first, we can suggest some useful inputs from the argument types, and let the user fill in the outputs.

**Comment by michaelbjames** [comment]
Well, heck that's our whole study now!
