### ISSUE TITLE
web todo: get more examples

### ISSUE THREAD

**Issue by aaronguo1996** [davidmrdavid/hoogle_plus#88]
When a user ask for more examples, we need to handle the response json string properly - display the new examples under that solution

**Comment by michaelbjames** [comment]
Can you give an example of a query that should be able to give more examples? When I tried `a -> [Maybe a] -> a`, I got nothing.

**Comment by aaronguo1996** [comment]
Type query: `a -> [Maybe a] -> a`
Example: `1 [Nothing, Nothing] ==> 1`
When you click more examples, you should get some examples back. The examples are in the format `[{"inputs": [str], "output": str}]`

**Comment by aaronguo1996** [comment]
The whole response is in the format `{"error": str, "examples": [{"inputs": [str], "output": str}]`

**Comment by michaelbjames** [comment]
https://github.com/davidmrdavid/hoogle_plus/pull/109
